apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: table-maintenance
spec:
  sparkImage:
    custom: "ghcr.io/battery-pulse/pulse-telemetry:latest" 
    productVersion: "3.5.1" 
    pullPolicy: IfNotPresent
  mainApplicationFile: local:////pulse-telemetry/src/pulse_telemetry/apps/table_maintenance.py
  env:
    - name: PULSE_TELEMETRY_CATALOG
      valueFrom:
        configMapKeyRef:
          name: table-maintenance-config
          key: PULSE_TELEMETRY_CATALOG
    - name: PULSE_TELEMETRY_DATABASE
      valueFrom:
        configMapKeyRef:
          name: table-maintenance-config
          key: PULSE_TELEMETRY_DATABASE
    - name: PULSE_TELEMETRY_OLDER_THAN_DAYS
      valueFrom:
        configMapKeyRef:
          name: table-maintenance-config
          key: PULSE_TELEMETRY_OLDER_THAN_DAYS
    - name: PULSE_TELEMETRY_RETAIN_LAST
      valueFrom:
        configMapKeyRef:
          name: table-maintenance-config
          key: PULSE_TELEMETRY_RETAIN_LAST
  sparkConf:
    spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    spark.sql.catalog.lakehouse: org.apache.iceberg.spark.SparkCatalog  # catalog name should match config map below
    spark.sql.catalog.lakehouse.type: hive
    spark.sql.catalog.lakehouse.uri: thrift://hive-metastore.default.svc:9083  # match your metastore address
    spark.sql.catalog.lakehouse.warehouse: s3a://lakehouse/  # set your warehouse directory
    spark.sql.session.timeZone: UTC
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1
      - org.apache.hadoop:hadoop-aws:3.3.4
  mode: cluster
  s3connection:
    reference: minio  # match your minio s3 connection
  driver:
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
  executor:
    replicas: 1
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: table-maintenance-config
data:
  PULSE_TELEMETRY_CATALOG: "lakehouse"
  PULSE_TELEMETRY_DATABASE: "dev"
  PULSE_TELEMETRY_OLDER_THAN_DAYS: "5"
  PULSE_TELEMETRY_RETAIN_LAST: "48"  # assuming hourly jobs, 2 days worth at minimum
