name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install

      - name: Get Release Version
        id: get_version
        run: echo "package_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/battery-pulse/pulse-telemetry:${{ env.package_version }} -t ghcr.io/battery-pulse/pulse-telemetry:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/battery-pulse/pulse-telemetry:${{ env.package_version }}
          docker push ghcr.io/battery-pulse/pulse-telemetry:latest
